[package]
name = "day-17"
version = "0.1.0"
authors = ["Alper Cugun-Gscheidel <alper.cugun-gscheidel@dcso.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.14.0"
itertools = "0.9.0"