[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Alper Çugun <github@alper.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.1"
image = "0.23.12"
crossbeam = "0.8.0"