[package]
name = "day-21"
version = "0.1.0"
authors = ["Alper Çugun <github@alper.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
